---

- name: Download Google signing key.
  shell: wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
  changed_when: no

- name: Download Spotify signing key.
  shell: apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 94558F59
  changed_when: no

- name: Add Spotify PPA.
  shell: sh -c 'echo "deb http://repository.spotify.com stable non-free" > /etc/apt/sources.list.d/spotify.list'
  changed_when: no

- name: Install basic packages.
  apt: 'pkg="{{ item }}" state=installed update-cache=yes'
  with_items: basic_packages

- name: Add PPAs.
  apt_repository: 'repo="{{ item }}"'
  with_items: ppas

- name: Install extra packages.
  apt: 'pkg="{{ item }}" state=installed'
  with_items: extra_packages

- name: Install Python packages.
  pip: name={{ item }}
  with_items: python_packages
  when: python_packages is defined

- name: Enable virtualenv shortcuts.
  lineinfile: "dest=~/.bashrc state=present regexp='^. /usr/local/bin/virtualenvwrapper.sh' line='. /usr/local/bin/virtualenvwrapper.sh'"

- name: Set local SSH config file.
  template: src=ssh_config.j2 dest=~/.ssh/config

- name: Install custom xkb mapping file (based on Crouton's keyboard target which must be installed first).
  copy: src=xkb-symbols-chromebook dest=/usr/share/X11/xkb/symbols/chromebook
  notify: clear xkb cache

- name: Get the current directory.
  shell: pwd
  register: pwd
  changed_when: no
  tags:
    - settings

- name: Link our settings files (the ones headed for our home directory)
  file: path=~/{{ item }} src={{ pwd.stdout }}/settings/{{ item }} state=link force=yes
  sudo: yes
  sudo_user: jamalex
  with_items:
    - .bashrc
    - .bash_aliases
  tags:
    - settings
